{
 "title": "schedule-server",
 "time": { "from": "2019-02-15T00:30:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "Start Schedule Counter",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "startScheduleCount" }
   ]
  },
  {
   "title": "Update Schedule Counter",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "updateScheduleCount" }
   ]
  },
  {
   "title": "View Schedule Counter",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "viewScheduleCount" }
   ]
  },
  {
   "title": "Remove Schedule Counter",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "removeScheduleCount" }
   ]
  },
  {
   "title": "Register Schedule Counter",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "registerScheduleCount" }
   ]
  },
  {
   "title": "registerScheduleCount",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "registerScheduleCount" }
   ]
  }
 ]
}